// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYdlU4J8_-xPpIm2XVZ0_hKG2aqRr-iRw',
    appId: '1:110008250:web:aa9b66abcf16745bffaf83',
    messagingSenderId: '110008250',
    projectId: 'expense-tracker-de702',
    authDomain: 'expense-tracker-de702.firebaseapp.com',
    databaseURL: 'https://expense-tracker-de702-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-de702.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXzZ6-KQ_D9j_aLOZkp4p-H-B8WSWN6g',
    appId: '1:110008250:android:35a78c872207de14ffaf83',
    messagingSenderId: '110008250',
    projectId: 'expense-tracker-de702',
    databaseURL: 'https://expense-tracker-de702-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-de702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmazO3wzvQZSO6QfHT1oQMgbrvV4wtwgQ',
    appId: '1:110008250:ios:dd14dbfb79bff939ffaf83',
    messagingSenderId: '110008250',
    projectId: 'expense-tracker-de702',
    databaseURL: 'https://expense-tracker-de702-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-de702.appspot.com',
    iosClientId: '110008250-256ot5ri362rg0aj6tbubn3fpsuv9p0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmazO3wzvQZSO6QfHT1oQMgbrvV4wtwgQ',
    appId: '1:110008250:ios:76bf81f4aadb8a9bffaf83',
    messagingSenderId: '110008250',
    projectId: 'expense-tracker-de702',
    databaseURL: 'https://expense-tracker-de702-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-de702.appspot.com',
    iosClientId: '110008250-54snvkv99se7hksr2t0ao1d4hdl3nh3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp.RunnerTests',
  );
}
